# Generated by Django 4.2.10 on 2024-08-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerz', '0005_event_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.CharField(max_length=50),
        ),
    ]
