# Generated by Django 4.2.10 on 2024-08-29 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamerz', '0006_alter_event_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamerz.client'),
        ),
    ]
