# Generated by Django 4.2.10 on 2024-08-29 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamerz', '0008_alter_ongoinggame_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ongoinggame',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
